name: developine_app
description: Flutter demo application.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Bloc for state management
  flutter_bloc: ^8.0.1
  # font awesome library.
  font_awesome_flutter: ^10.1.0
  # Value equality
  equatable: ^2.0.3
  # Service locator
  get_it: ^7.2.0
  # For Navigation and Themes.
  get: ^4.6.5

  # Functional programming in Dart.
  dartz: ^0.10.1

  # Local cache
  shared_preferences: ^2.0.15

  # Localization
  flutter_localizations:
    sdk: flutter
  # To add localized text.
  intl: ^0.17.0

  # Networking
  dio: ^4.0.6
  simple_connection_checker: ^0.2.1


  path: ^1.8.0
  path_provider: ^2.0.0
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.7

  # HTTP inspector tool.
  alice: ^0.2.5

  firebase_messaging: ^11.4.0
  firebase_crashlytics: ^2.8.0
  firebase_analytics: ^9.1.8
  firebase_core: ^1.17.0
  flutter_local_notifications: ^9.5.3+1
  flutter_flavorizr: ^2.1.3
  permission_handler: ^8.3.0
  location: ^4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true
  generate: true

